2020-06-08 10:35:15,245	INFO -- MainProcess _internal.py:113 --  * Running on https://0.0.0.0:5000/ (Press CTRL+C to quit)
2020-06-08 10:35:40,674	INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [08/Jun/2020 10:35:40] "[32mGET / HTTP/1.1[0m" 302 -
2020-06-08 10:35:40,925	INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [08/Jun/2020 10:35:40] "[32mGET /google/login HTTP/1.1[0m" 302 -
2020-06-08 10:35:42,958	INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [08/Jun/2020 10:35:42] "[32mGET / HTTP/1.1[0m" 302 -
2020-06-08 10:35:43,212	INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [08/Jun/2020 10:35:43] "[32mGET /google/login HTTP/1.1[0m" 302 -
2020-06-08 10:36:15,882	INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [08/Jun/2020 10:36:15] "[32mGET /google/auth?state=eIJSg87vpnwpOPHEa0p498XrjxtYIT&code=4/0gFZAcqdLuRcRgpgVpvj7ZtYRFtmotp6MZ0JpoBGe_LglzlC0q5GMmAznJMiy1rrdXXJK25tGUxj722rElhU8Sc&scope=email%20profile%20openid%20https://www.googleapis.com/auth/userinfo.email%20https://www.googleapis.com/auth/userinfo.profile&authuser=2&hd=ext.ml6.eu&prompt=consent HTTP/1.1[0m" 302 -
2020-06-08 10:36:58,850	INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [08/Jun/2020 10:36:58] "[37mGET / HTTP/1.1[0m" 200 -
2020-06-08 10:36:59,595	INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [08/Jun/2020 10:36:59] "[37mGET /static/css/screen.css HTTP/1.1[0m" 200 -
2020-06-08 10:36:59,602	INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [08/Jun/2020 10:36:59] "[37mGET /static/css/normalize.css HTTP/1.1[0m" 200 -
2020-06-08 10:36:59,608	INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [08/Jun/2020 10:36:59] "[33mGET /assets/fonts/Roboto-Regular.ttf HTTP/1.1[0m" 404 -
2020-06-08 10:36:59,613	INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [08/Jun/2020 10:36:59] "[33mGET /assets/fonts/Roboto-Medium.ttf HTTP/1.1[0m" 404 -
2020-06-08 10:36:59,617	INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [08/Jun/2020 10:36:59] "[33mGET /assets/fonts/Roboto-Bold.ttf HTTP/1.1[0m" 404 -
2020-06-08 10:36:59,895	INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [08/Jun/2020 10:36:59] "[37mGET /js/datahandler.js HTTP/1.1[0m" 200 -
2020-06-08 10:37:00,209	INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [08/Jun/2020 10:37:00] "[37mGET /js/start.js HTTP/1.1[0m" 200 -
2020-06-08 10:37:00,343	INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [08/Jun/2020 10:37:00] "[37mGET /socket.io/?EIO=3&transport=polling&t=NAJ4s2r HTTP/1.1[0m" 200 -
2020-06-08 10:37:00,829	ERROR -- MainProcess webserver.py:190 -- 'utf-8' codec can't decode byte 0x89 in position 0: invalid start byte
2020-06-08 10:37:00,829	ERROR -- MainProcess app.py:1891 -- Exception on /favicon-32x32.png [GET]
Traceback (most recent call last):
  File "C:\Users\tibov\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\tibov\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\app.py", line 1953, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\tibov\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\app.py", line 1968, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\tibov\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\app.py", line 2097, in make_response
    raise TypeError(
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
2020-06-08 10:37:00,834	INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [08/Jun/2020 10:37:00] "[35m[1mGET /favicon-32x32.png HTTP/1.1[0m" 500 -
2020-06-08 10:37:00,900	INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [08/Jun/2020 10:37:00] "[37mGET /manifest.json HTTP/1.1[0m" 200 -
2020-06-08 10:37:00,905	INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [08/Jun/2020 10:37:00] "[37mGET /api/v1/meetingbox/status HTTP/1.1[0m" 200 -
2020-06-08 10:37:00,961	ERROR -- MainProcess webserver.py:190 -- 'utf-8' codec can't decode byte 0x89 in position 0: invalid start byte
2020-06-08 10:37:00,962	ERROR -- MainProcess app.py:1891 -- Exception on /favicon-16x16.png [GET]
Traceback (most recent call last):
  File "C:\Users\tibov\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\tibov\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\app.py", line 1953, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\tibov\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\app.py", line 1968, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\tibov\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\app.py", line 2097, in make_response
    raise TypeError(
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
2020-06-08 10:37:00,963	INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [08/Jun/2020 10:37:00] "[35m[1mGET /favicon-16x16.png HTTP/1.1[0m" 500 -
2020-06-08 10:37:01,459	INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [08/Jun/2020 10:37:01] "[37mGET /api/v1/meetingbox/Kitchen/info HTTP/1.1[0m" 200 -
2020-06-08 10:37:05,122	INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [08/Jun/2020 10:37:05] "[37mGET /socket.io/?EIO=3&transport=polling&t=NAJ4s4z&sid=4e0b4c75d1ea4784b4ad5a9ec35dfaa5 HTTP/1.1[0m" 200 -
2020-06-08 10:37:16,122	INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [08/Jun/2020 10:37:16] "[37mGET /socket.io/?EIO=3&transport=polling&t=NAJ4tFb&sid=4e0b4c75d1ea4784b4ad5a9ec35dfaa5 HTTP/1.1[0m" 200 -
2020-06-08 10:37:18,321	INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [08/Jun/2020 10:37:18] "[37mGET /static/css/normalize.css HTTP/1.1[0m" 200 -
2020-06-08 10:37:18,937	INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [08/Jun/2020 10:37:18] "[37mGET /static/css/screen.css HTTP/1.1[0m" 200 -
2020-06-08 10:37:27,123	INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [08/Jun/2020 10:37:27] "[37mGET /socket.io/?EIO=3&transport=polling&t=NAJ4vxT&sid=4e0b4c75d1ea4784b4ad5a9ec35dfaa5 HTTP/1.1[0m" 200 -
2020-06-08 10:38:08,857	INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [08/Jun/2020 10:38:08] "[37mGET / HTTP/1.1[0m" 200 -
2020-06-08 10:38:09,505	INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [08/Jun/2020 10:38:09] "[37mGET /static/css/screen.css HTTP/1.1[0m" 200 -
2020-06-08 10:38:09,515	INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [08/Jun/2020 10:38:09] "[37mGET /static/css/normalize.css HTTP/1.1[0m" 200 -
2020-06-08 10:38:09,530	INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [08/Jun/2020 10:38:09] "[33mGET /assets/fonts/Roboto-Regular.ttf HTTP/1.1[0m" 404 -
2020-06-08 10:38:09,539	INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [08/Jun/2020 10:38:09] "[33mGET /assets/fonts/Roboto-Medium.ttf HTTP/1.1[0m" 404 -
2020-06-08 10:38:09,801	INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [08/Jun/2020 10:38:09] "[33mGET /assets/fonts/Roboto-Bold.ttf HTTP/1.1[0m" 404 -
2020-06-08 10:38:10,120	INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [08/Jun/2020 10:38:10] "[37mGET /js/start.js HTTP/1.1[0m" 200 -
2020-06-08 10:38:10,131	INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [08/Jun/2020 10:38:10] "[37mGET /js/datahandler.js HTTP/1.1[0m" 200 -
2020-06-08 10:38:10,246	INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [08/Jun/2020 10:38:10] "[37mGET /socket.io/?EIO=3&transport=polling&t=NAJ577S HTTP/1.1[0m" 200 -
2020-06-08 10:38:10,756	INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [08/Jun/2020 10:38:10] "[37mGET /api/v1/meetingbox/status HTTP/1.1[0m" 200 -
2020-06-08 10:38:10,775	ERROR -- MainProcess webserver.py:190 -- 'utf-8' codec can't decode byte 0x89 in position 0: invalid start byte
2020-06-08 10:38:10,776	ERROR -- MainProcess app.py:1891 -- Exception on /favicon-32x32.png [GET]
Traceback (most recent call last):
  File "C:\Users\tibov\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\tibov\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\app.py", line 1953, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\tibov\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\app.py", line 1968, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\tibov\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\app.py", line 2097, in make_response
    raise TypeError(
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
2020-06-08 10:38:10,778	INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [08/Jun/2020 10:38:10] "[35m[1mGET /favicon-32x32.png HTTP/1.1[0m" 500 -
2020-06-08 10:38:10,805	INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [08/Jun/2020 10:38:10] "[37mGET /manifest.json HTTP/1.1[0m" 200 -
2020-06-08 10:38:10,949	INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [08/Jun/2020 10:38:10] "[37mGET /api/v1/meetingbox/Kitchen/info HTTP/1.1[0m" 200 -
2020-06-08 10:38:11,126	INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [08/Jun/2020 10:38:11] "[37mGET /socket.io/?EIO=3&transport=polling&t=NAJ579H&sid=8604d8fbf9de4780923bf7e68002ed70 HTTP/1.1[0m" 200 -
2020-06-08 10:38:11,393	ERROR -- MainProcess webserver.py:190 -- 'utf-8' codec can't decode byte 0x89 in position 0: invalid start byte
2020-06-08 10:38:11,393	ERROR -- MainProcess app.py:1891 -- Exception on /favicon-16x16.png [GET]
Traceback (most recent call last):
  File "C:\Users\tibov\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\tibov\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\app.py", line 1953, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\tibov\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\app.py", line 1968, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\tibov\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\app.py", line 2097, in make_response
    raise TypeError(
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
2020-06-08 10:38:11,395	INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [08/Jun/2020 10:38:11] "[35m[1mGET /favicon-16x16.png HTTP/1.1[0m" 500 -
2020-06-08 10:38:22,127	INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [08/Jun/2020 10:38:22] "[37mGET /socket.io/?EIO=3&transport=polling&t=NAJ57Mv&sid=8604d8fbf9de4780923bf7e68002ed70 HTTP/1.1[0m" 200 -
2020-06-08 10:38:33,128	INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [08/Jun/2020 10:38:33] "[37mGET /socket.io/?EIO=3&transport=polling&t=NAJ5A2q&sid=8604d8fbf9de4780923bf7e68002ed70 HTTP/1.1[0m" 200 -
2020-06-08 10:38:35,861	INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [08/Jun/2020 10:38:35] "[37mPOST /socket.io/?EIO=3&transport=polling&t=NAJ5DFr&sid=8604d8fbf9de4780923bf7e68002ed70 HTTP/1.1[0m" 200 -
2020-06-08 10:38:35,861	INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [08/Jun/2020 10:38:35] "[37mGET /socket.io/?EIO=3&transport=polling&t=NAJ5Ckk&sid=8604d8fbf9de4780923bf7e68002ed70 HTTP/1.1[0m" 200 -
2020-06-08 10:38:44,129	INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [08/Jun/2020 10:38:44] "[37mGET /socket.io/?EIO=3&transport=polling&t=NAJ5DPR&sid=8604d8fbf9de4780923bf7e68002ed70 HTTP/1.1[0m" 200 -
2020-06-08 10:38:51,939	INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [08/Jun/2020 10:38:51] "[37mGET / HTTP/1.1[0m" 200 -
2020-06-08 10:38:52,584	INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [08/Jun/2020 10:38:52] "[37mGET /static/css/screen.css HTTP/1.1[0m" 200 -
2020-06-08 10:38:52,590	INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [08/Jun/2020 10:38:52] "[37mGET /static/css/normalize.css HTTP/1.1[0m" 200 -
2020-06-08 10:38:52,595	INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [08/Jun/2020 10:38:52] "[33mGET /assets/fonts/Roboto-Regular.ttf HTTP/1.1[0m" 404 -
2020-06-08 10:38:52,605	INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [08/Jun/2020 10:38:52] "[33mGET /assets/fonts/Roboto-Bold.ttf HTTP/1.1[0m" 404 -
2020-06-08 10:38:52,880	INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [08/Jun/2020 10:38:52] "[37mGET /js/datahandler.js HTTP/1.1[0m" 200 -
2020-06-08 10:38:52,909	INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [08/Jun/2020 10:38:52] "[33mGET /assets/fonts/Roboto-Medium.ttf HTTP/1.1[0m" 404 -
2020-06-08 10:38:53,197	ERROR -- MainProcess webserver.py:190 -- 'utf-8' codec can't decode byte 0x89 in position 0: invalid start byte
2020-06-08 10:38:53,197	ERROR -- MainProcess app.py:1891 -- Exception on /favicon-32x32.png [GET]
Traceback (most recent call last):
  File "C:\Users\tibov\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\tibov\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\app.py", line 1953, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\tibov\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\app.py", line 1968, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\tibov\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\app.py", line 2097, in make_response
    raise TypeError(
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
2020-06-08 10:38:53,200	INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [08/Jun/2020 10:38:53] "[35m[1mGET /favicon-32x32.png HTTP/1.1[0m" 500 -
2020-06-08 10:38:53,210	INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [08/Jun/2020 10:38:53] "[37mGET /js/start.js HTTP/1.1[0m" 200 -
2020-06-08 10:38:53,322	ERROR -- MainProcess webserver.py:190 -- 'utf-8' codec can't decode byte 0x89 in position 0: invalid start byte
2020-06-08 10:38:53,322	ERROR -- MainProcess app.py:1891 -- Exception on /favicon-16x16.png [GET]
Traceback (most recent call last):
  File "C:\Users\tibov\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\tibov\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\app.py", line 1953, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\tibov\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\app.py", line 1968, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\tibov\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\app.py", line 2097, in make_response
    raise TypeError(
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
2020-06-08 10:38:53,323	INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [08/Jun/2020 10:38:53] "[35m[1mGET /favicon-16x16.png HTTP/1.1[0m" 500 -
2020-06-08 10:38:53,818	INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [08/Jun/2020 10:38:53] "[37mGET /api/v1/meetingbox/status HTTP/1.1[0m" 200 -
2020-06-08 10:38:53,837	INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [08/Jun/2020 10:38:53] "[37mGET /socket.io/?EIO=3&transport=polling&t=NAJ5HeV HTTP/1.1[0m" 200 -
2020-06-08 10:38:53,837	INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [08/Jun/2020 10:38:53] "[37mGET /socket.io/?EIO=3&transport=polling&t=NAJ5FQc&sid=8604d8fbf9de4780923bf7e68002ed70 HTTP/1.1[0m" 200 -
2020-06-08 10:38:53,862	INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [08/Jun/2020 10:38:53] "[37mGET /manifest.json HTTP/1.1[0m" 200 -
2020-06-08 10:38:53,992	INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [08/Jun/2020 10:38:53] "[37mGET /api/v1/meetingbox/Kitchen/info HTTP/1.1[0m" 200 -
2020-06-08 10:38:55,130	INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [08/Jun/2020 10:38:55] "[37mGET /socket.io/?EIO=3&transport=polling&t=NAJ5HoO&sid=ff839736927b4e22b6ae48579181ae73 HTTP/1.1[0m" 200 -
2020-06-08 10:39:06,132	INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [08/Jun/2020 10:39:06] "[37mGET /socket.io/?EIO=3&transport=polling&t=NAJ5I6Y&sid=ff839736927b4e22b6ae48579181ae73 HTTP/1.1[0m" 200 -
2020-06-08 10:39:17,134	INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [08/Jun/2020 10:39:17] "[37mGET /socket.io/?EIO=3&transport=polling&t=NAJ5KoP&sid=ff839736927b4e22b6ae48579181ae73 HTTP/1.1[0m" 200 -
2020-06-08 10:39:18,852	INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [08/Jun/2020 10:39:18] "[37mPOST /socket.io/?EIO=3&transport=polling&t=NAJ5Nuz&sid=ff839736927b4e22b6ae48579181ae73 HTTP/1.1[0m" 200 -
2020-06-08 10:39:18,852	INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [08/Jun/2020 10:39:18] "[37mGET /socket.io/?EIO=3&transport=polling&t=NAJ5NUS&sid=ff839736927b4e22b6ae48579181ae73 HTTP/1.1[0m" 200 -
2020-06-08 10:39:28,135	INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [08/Jun/2020 10:39:28] "[37mGET /socket.io/?EIO=3&transport=polling&t=NAJ5NvB&sid=ff839736927b4e22b6ae48579181ae73 HTTP/1.1[0m" 200 -
2020-06-08 10:39:39,135	INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [08/Jun/2020 10:39:39] "[37mGET /socket.io/?EIO=3&transport=polling&t=NAJ5QAE&sid=ff839736927b4e22b6ae48579181ae73 HTTP/1.1[0m" 200 -
2020-06-08 10:39:43,862	INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [08/Jun/2020 10:39:43] "[37mPOST /socket.io/?EIO=3&transport=polling&t=NAJ5T_p&sid=ff839736927b4e22b6ae48579181ae73 HTTP/1.1[0m" 200 -
2020-06-08 10:39:43,863	INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [08/Jun/2020 10:39:43] "[37mGET /socket.io/?EIO=3&transport=polling&t=NAJ5Ss4&sid=ff839736927b4e22b6ae48579181ae73 HTTP/1.1[0m" 200 -
2020-06-08 10:39:50,137	INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [08/Jun/2020 10:39:50] "[37mGET /socket.io/?EIO=3&transport=polling&t=NAJ5T__&sid=ff839736927b4e22b6ae48579181ae73 HTTP/1.1[0m" 200 -
2020-06-08 10:40:31,839	INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [08/Jun/2020 10:40:31] "[37mGET / HTTP/1.1[0m" 200 -
2020-06-08 10:40:32,488	INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [08/Jun/2020 10:40:32] "[37mGET /static/css/screen.css HTTP/1.1[0m" 200 -
2020-06-08 10:40:32,496	INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [08/Jun/2020 10:40:32] "[37mGET /static/css/normalize.css HTTP/1.1[0m" 200 -
2020-06-08 10:40:32,524	INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [08/Jun/2020 10:40:32] "[33mGET /assets/fonts/Roboto-Regular.ttf HTTP/1.1[0m" 404 -
2020-06-08 10:40:32,527	INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [08/Jun/2020 10:40:32] "[33mGET /assets/fonts/Roboto-Medium.ttf HTTP/1.1[0m" 404 -
2020-06-08 10:40:32,782	INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [08/Jun/2020 10:40:32] "[33mGET /assets/fonts/Roboto-Bold.ttf HTTP/1.1[0m" 404 -
2020-06-08 10:40:33,112	INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [08/Jun/2020 10:40:33] "[37mGET /js/start.js HTTP/1.1[0m" 200 -
2020-06-08 10:40:33,118	INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [08/Jun/2020 10:40:33] "[37mGET /js/datahandler.js HTTP/1.1[0m" 200 -
2020-06-08 10:40:33,225	INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [08/Jun/2020 10:40:33] "[37mGET /socket.io/?EIO=3&transport=polling&t=NAJ5g1Z HTTP/1.1[0m" 200 -
2020-06-08 10:40:33,737	INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [08/Jun/2020 10:40:33] "[37mGET /api/v1/meetingbox/status HTTP/1.1[0m" 200 -
2020-06-08 10:40:33,753	ERROR -- MainProcess webserver.py:190 -- 'utf-8' codec can't decode byte 0x89 in position 0: invalid start byte
2020-06-08 10:40:33,753	ERROR -- MainProcess app.py:1891 -- Exception on /favicon-32x32.png [GET]
Traceback (most recent call last):
  File "C:\Users\tibov\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\tibov\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\app.py", line 1953, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\tibov\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\app.py", line 1968, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\tibov\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\app.py", line 2097, in make_response
    raise TypeError(
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
2020-06-08 10:40:33,755	INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [08/Jun/2020 10:40:33] "[35m[1mGET /favicon-32x32.png HTTP/1.1[0m" 500 -
2020-06-08 10:40:33,779	INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [08/Jun/2020 10:40:33] "[37mGET /manifest.json HTTP/1.1[0m" 200 -
2020-06-08 10:40:34,141	INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [08/Jun/2020 10:40:34] "[37mGET /socket.io/?EIO=3&transport=polling&t=NAJ5g3L&sid=0e69c51f8b59437aa7f691597125a8fa HTTP/1.1[0m" 200 -
2020-06-08 10:40:34,375	ERROR -- MainProcess webserver.py:190 -- 'utf-8' codec can't decode byte 0x89 in position 0: invalid start byte
2020-06-08 10:40:34,375	ERROR -- MainProcess app.py:1891 -- Exception on /favicon-16x16.png [GET]
Traceback (most recent call last):
  File "C:\Users\tibov\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\tibov\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\app.py", line 1953, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\tibov\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\app.py", line 1968, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\tibov\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\app.py", line 2097, in make_response
    raise TypeError(
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
2020-06-08 10:40:34,378	INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [08/Jun/2020 10:40:34] "[35m[1mGET /favicon-16x16.png HTTP/1.1[0m" 500 -
2020-06-08 10:40:34,414	INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [08/Jun/2020 10:40:34] "[37mGET /api/v1/meetingbox/Kitchen/info HTTP/1.1[0m" 200 -
2020-06-08 10:40:45,143	INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [08/Jun/2020 10:40:45] "[37mGET /socket.io/?EIO=3&transport=polling&t=NAJ5gHZ&sid=0e69c51f8b59437aa7f691597125a8fa HTTP/1.1[0m" 200 -
2020-06-08 10:40:56,144	INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [08/Jun/2020 10:40:56] "[37mGET /socket.io/?EIO=3&transport=polling&t=NAJ5izU&sid=0e69c51f8b59437aa7f691597125a8fa HTTP/1.1[0m" 200 -
2020-06-08 10:40:58,855	INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [08/Jun/2020 10:40:58] "[37mPOST /socket.io/?EIO=3&transport=polling&t=NAJ5m9t&sid=0e69c51f8b59437aa7f691597125a8fa HTTP/1.1[0m" 200 -
2020-06-08 10:40:58,855	INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [08/Jun/2020 10:40:58] "[37mGET /socket.io/?EIO=3&transport=polling&t=NAJ5lfS&sid=0e69c51f8b59437aa7f691597125a8fa HTTP/1.1[0m" 200 -
2020-06-08 10:41:07,145	INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [08/Jun/2020 10:41:07] "[37mGET /socket.io/?EIO=3&transport=polling&t=NAJ5mJl&sid=0e69c51f8b59437aa7f691597125a8fa HTTP/1.1[0m" 200 -
2020-06-08 10:41:14,772	INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [08/Jun/2020 10:41:14] "[37mGET / HTTP/1.1[0m" 200 -
2020-06-08 10:41:15,420	INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [08/Jun/2020 10:41:15] "[37mGET /static/css/screen.css HTTP/1.1[0m" 200 -
2020-06-08 10:41:15,426	INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [08/Jun/2020 10:41:15] "[37mGET /static/css/normalize.css HTTP/1.1[0m" 200 -
2020-06-08 10:41:15,431	INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [08/Jun/2020 10:41:15] "[33mGET /assets/fonts/Roboto-Regular.ttf HTTP/1.1[0m" 404 -
2020-06-08 10:41:15,438	INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [08/Jun/2020 10:41:15] "[33mGET /assets/fonts/Roboto-Medium.ttf HTTP/1.1[0m" 404 -
2020-06-08 10:41:15,448	INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [08/Jun/2020 10:41:15] "[33mGET /assets/fonts/Roboto-Bold.ttf HTTP/1.1[0m" 404 -
2020-06-08 10:41:15,719	INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [08/Jun/2020 10:41:15] "[37mGET /js/datahandler.js HTTP/1.1[0m" 200 -
2020-06-08 10:41:16,034	ERROR -- MainProcess webserver.py:190 -- 'utf-8' codec can't decode byte 0x89 in position 0: invalid start byte
2020-06-08 10:41:16,035	ERROR -- MainProcess app.py:1891 -- Exception on /favicon-32x32.png [GET]
Traceback (most recent call last):
  File "C:\Users\tibov\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\tibov\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\app.py", line 1953, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\tibov\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\app.py", line 1968, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\tibov\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\app.py", line 2097, in make_response
    raise TypeError(
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
2020-06-08 10:41:16,037	INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [08/Jun/2020 10:41:16] "[35m[1mGET /favicon-32x32.png HTTP/1.1[0m" 500 -
2020-06-08 10:41:16,042	INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [08/Jun/2020 10:41:16] "[37mGET /js/start.js HTTP/1.1[0m" 200 -
2020-06-08 10:41:16,157	ERROR -- MainProcess webserver.py:190 -- 'utf-8' codec can't decode byte 0x89 in position 0: invalid start byte
2020-06-08 10:41:16,157	ERROR -- MainProcess app.py:1891 -- Exception on /favicon-16x16.png [GET]
Traceback (most recent call last):
  File "C:\Users\tibov\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\tibov\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\app.py", line 1953, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\tibov\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\app.py", line 1968, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\tibov\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\app.py", line 2097, in make_response
    raise TypeError(
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
2020-06-08 10:41:16,159	INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [08/Jun/2020 10:41:16] "[35m[1mGET /favicon-16x16.png HTTP/1.1[0m" 500 -
2020-06-08 10:41:16,657	INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [08/Jun/2020 10:41:16] "[37mGET /api/v1/meetingbox/status HTTP/1.1[0m" 200 -
2020-06-08 10:41:16,679	INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [08/Jun/2020 10:41:16] "[37mGET /socket.io/?EIO=3&transport=polling&t=NAJ5qWJ HTTP/1.1[0m" 200 -
2020-06-08 10:41:16,680	INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [08/Jun/2020 10:41:16] "[37mGET /socket.io/?EIO=3&transport=polling&t=NAJ5oLE&sid=0e69c51f8b59437aa7f691597125a8fa HTTP/1.1[0m" 200 -
2020-06-08 10:41:16,697	INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [08/Jun/2020 10:41:16] "[37mGET /manifest.json HTTP/1.1[0m" 200 -
2020-06-08 10:41:16,844	INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [08/Jun/2020 10:41:16] "[37mGET /api/v1/meetingbox/Kitchen/info HTTP/1.1[0m" 200 -
2020-06-08 10:41:18,145	INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [08/Jun/2020 10:41:18] "[37mGET /socket.io/?EIO=3&transport=polling&t=NAJ5qgT&sid=327c67571c5345819a7ef8a4b10b5df0 HTTP/1.1[0m" 200 -
2020-06-08 10:41:29,147	INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [08/Jun/2020 10:41:29] "[37mGET /socket.io/?EIO=3&transport=polling&t=NAJ5r15&sid=327c67571c5345819a7ef8a4b10b5df0 HTTP/1.1[0m" 200 -
2020-06-08 10:41:40,147	INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [08/Jun/2020 10:41:40] "[37mGET /socket.io/?EIO=3&transport=polling&t=NAJ5tjB&sid=327c67571c5345819a7ef8a4b10b5df0 HTTP/1.1[0m" 200 -
2020-06-08 10:41:42,359	INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [08/Jun/2020 10:41:42] "[37mPOST /socket.io/?EIO=3&transport=polling&t=NAJ5wxK&sid=327c67571c5345819a7ef8a4b10b5df0 HTTP/1.1[0m" 200 -
2020-06-08 10:41:42,360	INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [08/Jun/2020 10:41:42] "[37mGET /socket.io/?EIO=3&transport=polling&t=NAJ5wOs&sid=327c67571c5345819a7ef8a4b10b5df0 HTTP/1.1[0m" 200 -
2020-06-08 10:41:51,148	INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [08/Jun/2020 10:41:51] "[37mGET /socket.io/?EIO=3&transport=polling&t=NAJ5wxY&sid=327c67571c5345819a7ef8a4b10b5df0 HTTP/1.1[0m" 200 -
2020-06-08 10:42:02,149	INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [08/Jun/2020 10:42:02] "[37mGET /socket.io/?EIO=3&transport=polling&t=NAJ5z4n&sid=327c67571c5345819a7ef8a4b10b5df0 HTTP/1.1[0m" 200 -
2020-06-08 10:42:08,358	INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [08/Jun/2020 10:42:08] "[37mPOST /socket.io/?EIO=3&transport=polling&t=NAJ61HY&sid=327c67571c5345819a7ef8a4b10b5df0 HTTP/1.1[0m" 200 -
2020-06-08 10:42:08,358	INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [08/Jun/2020 10:42:08] "[37mGET /socket.io/?EIO=3&transport=polling&t=NAJ5_me&sid=327c67571c5345819a7ef8a4b10b5df0 HTTP/1.1[0m" 200 -
2020-06-08 10:42:13,150	INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [08/Jun/2020 10:42:13] "[37mGET /socket.io/?EIO=3&transport=polling&t=NAJ61Hh&sid=327c67571c5345819a7ef8a4b10b5df0 HTTP/1.1[0m" 200 -
2020-06-08 10:42:24,152	INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [08/Jun/2020 10:42:24] "[37mGET /socket.io/?EIO=3&transport=polling&t=NAJ62St&sid=327c67571c5345819a7ef8a4b10b5df0 HTTP/1.1[0m" 200 -
2020-06-08 10:58:59,478	INFO -- MainProcess _internal.py:113 --  * Running on https://0.0.0.0:5000/ (Press CTRL+C to quit)
2020-06-08 10:59:27,674	INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [08/Jun/2020 10:59:27] "[37mGET /socket.io/?EIO=3&transport=polling&t=NAJ9-xx HTTP/1.1[0m" 200 -
2020-06-08 10:59:28,012	INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [08/Jun/2020 10:59:28] "[37mGET / HTTP/1.1[0m" 200 -
2020-06-08 10:59:32,375	INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [08/Jun/2020 10:59:32] "[37mGET /socket.io/?EIO=3&transport=polling&t=NAJ9_10&sid=775d449a21884b8ba20c639038d2a0e6 HTTP/1.1[0m" 200 -
2020-06-08 10:59:34,671	INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [08/Jun/2020 10:59:34] "[37mGET /static/css/screen.css HTTP/1.1[0m" 200 -
2020-06-08 10:59:34,676	INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [08/Jun/2020 10:59:34] "[37mGET /static/css/normalize.css HTTP/1.1[0m" 200 -
2020-06-08 10:59:34,680	INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [08/Jun/2020 10:59:34] "[33mGET /assets/fonts/Roboto-Regular.ttf HTTP/1.1[0m" 404 -
2020-06-08 10:59:34,688	INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [08/Jun/2020 10:59:34] "[33mGET /assets/fonts/Roboto-Medium.ttf HTTP/1.1[0m" 404 -
2020-06-08 10:59:34,693	INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [08/Jun/2020 10:59:34] "[33mGET /assets/fonts/Roboto-Bold.ttf HTTP/1.1[0m" 404 -
2020-06-08 10:59:41,368	INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [08/Jun/2020 10:59:41] "[37mGET /js/datahandler.js HTTP/1.1[0m" 200 -
2020-06-08 10:59:41,678	INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [08/Jun/2020 10:59:41] "[37mGET /js/start.js HTTP/1.1[0m" 200 -
2020-06-08 10:59:41,682	INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [08/Jun/2020 10:59:41] "[33mGET /cache.appcache HTTP/1.1[0m" 404 -
2020-06-08 10:59:43,376	INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [08/Jun/2020 10:59:43] "[37mGET /socket.io/?EIO=3&transport=polling&t=NAJA0AQ&sid=775d449a21884b8ba20c639038d2a0e6 HTTP/1.1[0m" 200 -
2020-06-08 10:59:48,671	INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [08/Jun/2020 10:59:48] "[37mGET /socket.io/?EIO=3&transport=polling&t=NAJA2Rq HTTP/1.1[0m" 200 -
2020-06-08 10:59:48,678	INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [08/Jun/2020 10:59:48] "[37mGET /api/v1/meetingbox/status HTTP/1.1[0m" 200 -
2020-06-08 10:59:48,690	INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [08/Jun/2020 10:59:48] "[37mGET /manifest.json HTTP/1.1[0m" 200 -
2020-06-08 10:59:48,694	ERROR -- MainProcess webserver.py:190 -- 'utf-8' codec can't decode byte 0x89 in position 0: invalid start byte
2020-06-08 10:59:48,694	ERROR -- MainProcess app.py:1891 -- Exception on /favicon-32x32.png [GET]
Traceback (most recent call last):
  File "C:\Users\tibov\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\tibov\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\app.py", line 1953, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\tibov\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\app.py", line 1968, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\tibov\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\app.py", line 2097, in make_response
    raise TypeError(
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
2020-06-08 10:59:48,697	INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [08/Jun/2020 10:59:48] "[35m[1mGET /favicon-32x32.png HTTP/1.1[0m" 500 -
2020-06-08 10:59:48,703	INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [08/Jun/2020 10:59:48] "[37mGET /socket.io/?EIO=3&transport=polling&t=NAJA2sK&sid=775d449a21884b8ba20c639038d2a0e6 HTTP/1.1[0m" 200 -
2020-06-08 10:59:48,849	INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [08/Jun/2020 10:59:48] "[37mGET /api/v1/meetingbox/Kitchen/info HTTP/1.1[0m" 200 -
2020-06-08 10:59:55,688	INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [08/Jun/2020 10:59:55] "[37mGET /socket.io/?EIO=3&transport=polling&t=NAJA497&sid=1cf2fdb6239d418f8ad0f692057b109f HTTP/1.1[0m" 200 -
2020-06-08 10:59:55,695	ERROR -- MainProcess webserver.py:190 -- 'utf-8' codec can't decode byte 0x89 in position 0: invalid start byte
2020-06-08 10:59:55,695	ERROR -- MainProcess app.py:1891 -- Exception on /favicon-16x16.png [GET]
Traceback (most recent call last):
  File "C:\Users\tibov\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\tibov\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\app.py", line 1953, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\tibov\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\app.py", line 1968, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\tibov\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\app.py", line 2097, in make_response
    raise TypeError(
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
2020-06-08 10:59:55,698	INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [08/Jun/2020 10:59:55] "[35m[1mGET /favicon-16x16.png HTTP/1.1[0m" 500 -
2020-06-08 10:59:55,702	INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [08/Jun/2020 10:59:55] "[37mGET /socket.io/?EIO=3&transport=polling&t=NAJA49Y&sid=775d449a21884b8ba20c639038d2a0e6 HTTP/1.1[0m" 200 -
2020-06-08 10:59:55,709	INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [08/Jun/2020 10:59:55] "[37mPOST /socket.io/?EIO=3&transport=polling&t=NAJA5IB&sid=775d449a21884b8ba20c639038d2a0e6 HTTP/1.1[0m" 200 -
2020-06-08 11:00:54,976	INFO -- MainProcess _internal.py:113 --  * Running on https://0.0.0.0:5000/ (Press CTRL+C to quit)
2020-06-08 11:03:31,546	INFO -- MainProcess _internal.py:113 --  * Running on https://0.0.0.0:5000/ (Press CTRL+C to quit)
2020-06-08 11:03:45,664	ERROR -- MainProcess app.py:1891 -- Exception on / [GET]
Traceback (most recent call last):
  File "C:\Users\tibov\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\tibov\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\tibov\AppData\Local\Programs\Python\Python38\lib\site-packages\flask_cors\extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\tibov\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\tibov\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\tibov\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\tibov\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
TypeError: index() missing 1 required positional argument: 'page'
2020-06-08 11:03:45,668	INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [08/Jun/2020 11:03:45] "[35m[1mGET / HTTP/1.1[0m" 500 -
2020-06-08 11:03:45,670	INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [08/Jun/2020 11:03:45] "[37mGET /socket.io/?EIO=3&transport=polling&t=NAJAzxB HTTP/1.1[0m" 200 -
2020-06-08 11:03:53,004	ERROR -- MainProcess webserver.py:162 -- favicon.ico.html
2020-06-08 11:03:53,005	ERROR -- MainProcess app.py:1891 -- Exception on /favicon.ico [GET]
Traceback (most recent call last):
  File "C:\Users\tibov\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\tibov\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\app.py", line 1953, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\tibov\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\app.py", line 1968, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\tibov\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\app.py", line 2097, in make_response
    raise TypeError(
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
2020-06-08 11:03:53,009	INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [08/Jun/2020 11:03:53] "[35m[1mGET /favicon.ico HTTP/1.1[0m" 500 -
2020-06-08 11:03:53,280	INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [08/Jun/2020 11:03:53] "[37mGET /socket.io/?EIO=3&transport=polling&t=NAJA-0A&sid=96da1886ac1c426186fb8b3889575c19 HTTP/1.1[0m" 200 -
2020-06-08 11:04:01,862	INFO -- MainProcess _internal.py:113 --  * Running on https://0.0.0.0:5000/ (Press CTRL+C to quit)
2020-06-08 11:04:13,669	INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [08/Jun/2020 11:04:13] "[37mGET /socket.io/?EIO=3&transport=polling&t=NAJB4HR HTTP/1.1[0m" 200 -
2020-06-08 11:04:13,890	INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [08/Jun/2020 11:04:13] "[37mGET / HTTP/1.1[0m" 200 -
2020-06-08 11:04:13,937	INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [08/Jun/2020 11:04:13] "[33mGET /assets/fonts/Roboto-Regular.ttf HTTP/1.1[0m" 404 -
2020-06-08 11:04:20,671	INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [08/Jun/2020 11:04:20] "[37mGET /static/css/normalize.css HTTP/1.1[0m" 200 -
2020-06-08 11:04:20,675	INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [08/Jun/2020 11:04:20] "[37mGET /static/css/screen.css HTTP/1.1[0m" 200 -
2020-06-08 11:04:20,679	INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [08/Jun/2020 11:04:20] "[33mGET /assets/fonts/Roboto-Medium.ttf HTTP/1.1[0m" 404 -
2020-06-08 11:04:20,683	INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [08/Jun/2020 11:04:20] "[33mGET /assets/fonts/Roboto-Bold.ttf HTTP/1.1[0m" 404 -
2020-06-08 11:04:23,600	INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [08/Jun/2020 11:04:23] "[37mGET /socket.io/?EIO=3&transport=polling&t=NAJB4rf&sid=e7a0b6a6c0974998a9c6defcc8468317 HTTP/1.1[0m" 200 -
2020-06-08 11:04:27,362	INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [08/Jun/2020 11:04:27] "[37mGET /js/datahandler.js HTTP/1.1[0m" 200 -
2020-06-08 11:04:27,672	INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [08/Jun/2020 11:04:27] "[37mGET /js/start.js HTTP/1.1[0m" 200 -
2020-06-08 11:04:27,911	ERROR -- MainProcess webserver.py:162 -- cache.appcache.html
2020-06-08 11:04:27,911	ERROR -- MainProcess app.py:1891 -- Exception on /cache.appcache [GET]
Traceback (most recent call last):
  File "C:\Users\tibov\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\tibov\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\app.py", line 1953, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\tibov\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\app.py", line 1968, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\tibov\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\app.py", line 2097, in make_response
    raise TypeError(
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
2020-06-08 11:04:27,914	INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [08/Jun/2020 11:04:27] "[35m[1mGET /cache.appcache HTTP/1.1[0m" 500 -
2020-06-08 11:04:34,601	INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [08/Jun/2020 11:04:34] "[37mGET /socket.io/?EIO=3&transport=polling&t=NAJB7Gp&sid=e7a0b6a6c0974998a9c6defcc8468317 HTTP/1.1[0m" 200 -
2020-06-08 11:04:34,674	INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [08/Jun/2020 11:04:34] "[37mGET /socket.io/?EIO=3&transport=polling&t=NAJB8GU HTTP/1.1[0m" 200 -
2020-06-08 11:04:34,678	INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [08/Jun/2020 11:04:34] "[37mGET /api/v1/meetingbox/status HTTP/1.1[0m" 200 -
2020-06-08 11:04:34,688	INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [08/Jun/2020 11:04:34] "[37mGET /manifest.json HTTP/1.1[0m" 200 -
2020-06-08 11:04:34,691	ERROR -- MainProcess webserver.py:201 -- 'utf-8' codec can't decode byte 0x89 in position 0: invalid start byte
2020-06-08 11:04:34,691	ERROR -- MainProcess app.py:1891 -- Exception on /favicon-32x32.png [GET]
Traceback (most recent call last):
  File "C:\Users\tibov\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\tibov\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\app.py", line 1953, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\tibov\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\app.py", line 1968, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\tibov\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\app.py", line 2097, in make_response
    raise TypeError(
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
2020-06-08 11:04:34,693	INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [08/Jun/2020 11:04:34] "[35m[1mGET /favicon-32x32.png HTTP/1.1[0m" 500 -
2020-06-08 11:04:34,843	INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [08/Jun/2020 11:04:34] "[37mGET /api/v1/meetingbox/Kitchen/info HTTP/1.1[0m" 200 -
2020-06-08 11:04:41,374	INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [08/Jun/2020 11:04:41] "[37mGET /socket.io/?EIO=3&transport=polling&t=NAJB9yi&sid=e7a0b6a6c0974998a9c6defcc8468317 HTTP/1.1[0m" 200 -
2020-06-08 11:04:41,673	ERROR -- MainProcess webserver.py:201 -- 'utf-8' codec can't decode byte 0x89 in position 0: invalid start byte
2020-06-08 11:04:41,673	ERROR -- MainProcess app.py:1891 -- Exception on /favicon-16x16.png [GET]
Traceback (most recent call last):
  File "C:\Users\tibov\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\tibov\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\app.py", line 1953, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\tibov\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\app.py", line 1968, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\tibov\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\app.py", line 2097, in make_response
    raise TypeError(
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
2020-06-08 11:04:41,676	INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [08/Jun/2020 11:04:41] "[35m[1mGET /favicon-16x16.png HTTP/1.1[0m" 500 -
2020-06-08 11:04:41,685	INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [08/Jun/2020 11:04:41] "[37mPOST /socket.io/?EIO=3&transport=polling&t=NAJBB6x&sid=e7a0b6a6c0974998a9c6defcc8468317 HTTP/1.1[0m" 200 -
2020-06-08 11:04:45,602	INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [08/Jun/2020 11:04:45] "[37mGET /socket.io/?EIO=3&transport=polling&t=NAJB9zt&sid=27530ec67ba24db5989f976fbd44dd09 HTTP/1.1[0m" 200 -
2020-06-08 11:04:48,363	INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [08/Jun/2020 11:04:48] "[37mGET /socket.io/?EIO=3&transport=polling&t=NAJBBcf&sid=e7a0b6a6c0974998a9c6defcc8468317 HTTP/1.1[0m" 200 -
2020-06-08 11:04:56,603	INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [08/Jun/2020 11:04:56] "[37mGET /socket.io/?EIO=3&transport=polling&t=NAJBDJo&sid=e7a0b6a6c0974998a9c6defcc8468317 HTTP/1.1[0m" 200 -
2020-06-08 11:04:56,603	INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [08/Jun/2020 11:04:56] "[37mGET /socket.io/?EIO=3&transport=polling&t=NAJBCea&sid=27530ec67ba24db5989f976fbd44dd09 HTTP/1.1[0m" 200 -
2020-06-08 11:05:02,675	INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [08/Jun/2020 11:05:02] "[37mPOST /socket.io/?EIO=3&transport=polling&t=NAJBG4V&sid=27530ec67ba24db5989f976fbd44dd09 HTTP/1.1[0m" 200 -
2020-06-08 11:05:02,675	INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [08/Jun/2020 11:05:02] "[37mGET /socket.io/?EIO=3&transport=polling&t=NAJBFKV&sid=27530ec67ba24db5989f976fbd44dd09 HTTP/1.1[0m" 200 -
2020-06-08 11:05:02,894	INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [08/Jun/2020 11:05:02] "[37mGET /calendar HTTP/1.1[0m" 200 -
2020-06-08 11:05:07,604	INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [08/Jun/2020 11:05:07] "[37mGET /socket.io/?EIO=3&transport=polling&t=NAJBFKV&sid=e7a0b6a6c0974998a9c6defcc8468317 HTTP/1.1[0m" 200 -
2020-06-08 11:05:09,669	INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [08/Jun/2020 11:05:09] "[37mGET /css/screen.css HTTP/1.1[0m" 200 -
2020-06-08 11:05:09,675	INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [08/Jun/2020 11:05:09] "[37mGET /css/normalize.css HTTP/1.1[0m" 200 -
2020-06-08 11:05:09,677	INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [08/Jun/2020 11:05:09] "[33mGET /assets/fonts/Roboto-Regular.ttf HTTP/1.1[0m" 404 -
2020-06-08 11:05:09,682	INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [08/Jun/2020 11:05:09] "[33mGET /assets/fonts/Roboto-Medium.ttf HTTP/1.1[0m" 404 -
2020-06-08 11:05:09,684	INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [08/Jun/2020 11:05:09] "[33mGET /assets/fonts/Roboto-Bold.ttf HTTP/1.1[0m" 404 -
2020-06-08 11:05:16,364	INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [08/Jun/2020 11:05:16] "[37mGET /js/datahandler.js HTTP/1.1[0m" 200 -
2020-06-08 11:05:16,677	INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [08/Jun/2020 11:05:16] "[37mGET /js/start.js HTTP/1.1[0m" 200 -
2020-06-08 11:05:16,679	INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [08/Jun/2020 11:05:16] "[31m[1mPOST /socket.io/?EIO=3&transport=polling&t=NAJBJfq&sid=e7a0b6a6c0974998a9c6defcc8468317 HTTP/1.1[0m" 400 -
2020-06-08 11:05:16,682	INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [08/Jun/2020 11:05:16] "[35m[1mGET /socket.io/?EIO=3&transport=polling&t=NAJBI0N&sid=e7a0b6a6c0974998a9c6defcc8468317 HTTP/1.1[0m" 500 -
2020-06-08 11:05:16,684	ERROR -- MainProcess _internal.py:113 -- Error on request:
Traceback (most recent call last):
  File "C:\Users\tibov\AppData\Local\Programs\Python\Python38\Lib\site-packages\werkzeug\serving.py", line 323, in run_wsgi
    execute(self.server.app)
  File "C:\Users\tibov\AppData\Local\Programs\Python\Python38\Lib\site-packages\werkzeug\serving.py", line 312, in execute
    application_iter = app(environ, start_response)
  File "C:\Users\tibov\AppData\Local\Programs\Python\Python38\Lib\site-packages\flask\app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\Users\tibov\AppData\Local\Programs\Python\Python38\Lib\site-packages\flask_socketio\__init__.py", line 45, in __call__
    return super(_SocketIOMiddleware, self).__call__(environ,
  File "C:\Users\tibov\AppData\Local\Programs\Python\Python38\Lib\site-packages\engineio\middleware.py", line 60, in __call__
    return self.engineio_app.handle_request(environ, start_response)
  File "C:\Users\tibov\AppData\Local\Programs\Python\Python38\Lib\site-packages\socketio\server.py", line 558, in handle_request
    return self.eio.handle_request(environ, start_response)
  File "C:\Users\tibov\AppData\Local\Programs\Python\Python38\Lib\site-packages\engineio\server.py", line 374, in handle_request
    socket = self._get_socket(sid)
  File "C:\Users\tibov\AppData\Local\Programs\Python\Python38\Lib\site-packages\engineio\server.py", line 562, in _get_socket
    raise KeyError('Session is disconnected')
KeyError: 'Session is disconnected'
2020-06-08 11:05:23,678	INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [08/Jun/2020 11:05:23] "[37mGET /css/screen.css HTTP/1.1[0m" 200 -
2020-06-08 11:05:23,689	INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [08/Jun/2020 11:05:23] "[37mGET /css/normalize.css HTTP/1.1[0m" 200 -
2020-06-08 11:05:23,690	INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [08/Jun/2020 11:05:23] "[37mGET /manifest.json HTTP/1.1[0m" 200 -
2020-06-08 11:05:23,694	INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [08/Jun/2020 11:05:23] "[37mGET /socket.io/?EIO=3&transport=polling&t=NAJBKEA HTTP/1.1[0m" 200 -
2020-06-08 11:05:23,871	INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [08/Jun/2020 11:05:23] "[37mGET /api/v1/meetingbox/Kitchen/info HTTP/1.1[0m" 200 -
2020-06-08 11:05:30,388	INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [08/Jun/2020 11:05:30] "[37mGET /socket.io/?EIO=3&transport=polling&t=NAJBKty HTTP/1.1[0m" 200 -
2020-06-08 11:05:30,617	ERROR -- MainProcess webserver.py:162 -- sw.js.html
2020-06-08 11:05:30,617	ERROR -- MainProcess app.py:1891 -- Exception on /sw.js [GET]
Traceback (most recent call last):
  File "C:\Users\tibov\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\tibov\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\app.py", line 1953, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\tibov\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\app.py", line 1968, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\tibov\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\app.py", line 2097, in make_response
    raise TypeError(
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
2020-06-08 11:05:30,619	INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [08/Jun/2020 11:05:30] "[35m[1mGET /sw.js HTTP/1.1[0m" 500 -
2020-06-08 11:05:30,679	INFO -- MainProcess _internal.py:113 -- 127.0.0.1 - - [08/Jun/2020 11:05:30] "[31m[1mPOST /socket.io/?EIO=3&transport=polling&t=NAJBKOi&sid=e7a0b6a6c0974998a9c6defcc8468317 HTTP/1.1[0m" 400 -
